tokenizer_source: full
device: auto
dtype: bfloat16
attention_implementation: eager

models:
  full:
    repo_id: open-unlearning/tofu_Llama-3.2-1B-Instruct_full
    revision: 88e31200b97e4c0c04ae0d2f0b591f427046d192
  retain:
    repo_id: open-unlearning/tofu_Llama-3.2-1B-Instruct_retain90
    revision: 7114300c0049527a71833f5683965c358ad9dcbf

expected_architecture:
  model_type: llama
  decoder_layers: 16
  hidden_size: 2048

